open-quantum-safe/liboqs-rust

oqs/src/lib.rs

`Once::call_once` takes `&self` and not `&mut self`. This is part of what makes it a synchronization primitive. As a result, the static does not need to be mutable and the call does not need to be unsafe. Only the FFI function call itself is unsafe here.

Make static INIT not mut and don't call it unsafely

---

oqs/src/lib.rs

Very small nitpicky PR. Sorry about that. But `#[must_use]` is not needed here as it's just a type alias. That property will carry over automatically from `std::result::Result`.

Remove redundant #[must_use]

---

LICENSE-APACHE2
LICENSE-MIT
README.md

Extended the README with parts that are present in other liboqs wrapper READMEs.  Still missing several parts, @thomwiggers can you assist?  See e.g. [liboqs-cpp/README.md](https://github.com/open-quantum-safe/liboqs-cpp/blob/master/README.md) or [liboqs-python/README.md](https://github.com/open-quantum-safe/liboqs-python/blob/master/README.md) for examples.
Also, is it okay to rename it to `liboqs-rs` to be consistent with our naming scheme for our other language wrappers?

Add OQS boilerplate

---

.github/workflows/docs.yml
README.md

It's now able to use GITHUB_TOKEN which is available by default AIUI.

Fix deploying docs to GH pages

---

oqs-sys/build.rs

For those running a system that (tragically) only has gcc based toolchains by default, this speeds up the compilation failure that tells you `libclang` is missing:
```
Compiling oqs-sys v0.3.0 (/liboqs-rust/oqs-sys)
error: failed to run custom build command for `oqs-sys v0.3.0 (/liboqs-rust/oqs-sys)`
Caused by:
process didn't exit successfully: `liboqs-rust/target/debug/build/oqs-sys-17a5bc04ec449e4a/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'Unable to find libclang: "couldn\'t find any valid shared libraries matching: [\'libclang.so\', \'libclang-*.so\', \'libclang.so.*\', \'libclang-*.so.*\'], set the `LIBCLANG_PATH` environment variable to a path where one of these files can be found (invalid: [])"', …
```

Ensure Clang is present before attempting to compile liboqs

---

oqs-sys/Cargo.toml
oqs/Cargo.toml

We won't publish before liboqs 0.5 though.

Bump the version number for next release

---

oqs-sys/build.rs
oqs-sys/src/lib.rs

Generate bindings to the random API exposed by liboqs (ie. https://github.com/open-quantum-safe/liboqs/blob/main/src/common/rand/rand.h)

Expose random API

---

oqs-sys/Cargo.toml
oqs/Cargo.toml

* NTRU level 5 algorithms
* NTRUPrime level 5 algorithms
* Be able to extract Algorithm from Sig/Kem
* Invert no_std feature (breaking, sorry!)
* Implement Display, Hash, Eq for Kem, Sig
* Implement Display for Algorithm
* Add NTRU level 5 parameter sets (ntruhps40961229, ntruhrss1373)
* Add NTRU Prime level 5 parameter sets (ntrulpr1277, sntrup1277)
* Add ARMv8 aarch64 optimized implementations of Kyber and SABER
* Minor updates to Kyber, NTRU, NTRU Prime, and SIKE implementations
* Minor updates to Dilithium implementation
* Optimized AES implementation on ARMv8 with crypto extensions.
* Preliminary support for building on S390x platform
* Improved build configurations on ARM platforms
* Improvements to benchmarking harness, with improved precision on ARM platforms
See also …

Release liboqs 0.7.1

---

.github/workflows/ci.yml

* The `actions-rs/*` components are no longer maintained. https://github.com/actions-rs/toolchain/issues/216
* Github changed how they package OpenSSL on the windows default images: https://github.com/actions/runner-images/pull/7337

Get rid of actions-rs actions and fix OpenSSL location on Windows

---

.github/workflows/ci.yml

This avoids https://github.com/rust-lang/rustup/issues/3189 which is triggered on Github Actions Windows runners.

Don't update Rustup in CI builds

---

.github/workflows/ci.yml
oqs-sys/build.rs

This went unnoticed because it was not tested in CI
See https://github.com/open-quantum-safe/liboqs-rust/pull/180#issuecomment-1694399607

Don't build NTRU prime if feature is not enabled

---

README.md
oqs-sys/Cargo.toml
oqs-sys/build.rs
oqs/Cargo.toml

Addresses #190 
Adds necessary changes to optionally detect the system liboqs version and link to it.
To consider:
- Should there be a `vendor` feature, or can we defer to `pkg-config` crate's env var configuration (e.g. "LIBOQS_NO_PKG_CONFIG")
- Is targeting the minor version (>= `0.8.0` && < `0.9.0`) enough?
Tested this manually with a system-installed build of liboqs 0.8.0-rc1. Not sure how best to test this in CI yet.

Allow finding and linking system deps

---

README.md
oqs-sys/build.rs

- Allow using LIBOQS_NO_VENDOR env var to force system liboqs
- Document the LIBOQS_NO_VENDOR env variable

build: Add LIBOQS_NO_VENDOR env variable

---

.github/dependabot.yml
.github/workflows/lint-pr.yml

Forces all PRs to use http://conventionalcommits.org from now on.

ci: Enforce conventional commit PRs

---

oqs-sys/build.rs

This allows to set the `OQS_PERMIT_UNSUPOPORTED_ARCHITECTURE` CMake option via an environment variable.

feat(liboqs): allow setting `OQS_PERMIT_UNSUPPORTED_ARCHITECTURE` CMake option via environment variable 

---

oqs-sys/build.rs

Noticed this part wasn't touched after the versioning update, this works correctly with it.

fix: adjust liboqs pkgconfig version detection to new scheme

---

.github/workflows/ci.yml

This PR does two things in preparation for updating to liboqs 0.12.0:
* Adds a repository_dispatch trigger to CI.
* Fixes path to OpenSSL for macos-latest in GitHub Actions.
The first two items will allow us to trigger CI from liboqs as we do for the other language wrappers and adapt to breaking changes as they occur. When I do the update to 0.12.0 I will add CI jobs that test against liboqs main to take advantage of this functionality. (Right now CI breaks with liboqs main.)

ci: Fix OpenSSL path, add repository_dispatch trigger

---

.github/workflows/ci.yml
CHANGELOG.md
README.md
oqs-sys/Cargo.toml
oqs-sys/README.md
oqs-sys/build.rs
oqs/Cargo.toml
oqs/README.md
oqs/src/kem.rs
oqs/src/lib.rs
oqs/src/sig.rs

This PR brings liboqs-rust in sync with liboqs version 0.12.0. Notably, this includes
- additions of ML-KEM, ML-DSA, MAYO, and CROSS
- updates to HQC and Falcon
- new signature APIs for signing and verifying with a context string.
Since liboqs 0.12.0 was just released, this PR also brings liboqs-rust in sync with the liboqs main branch. With an eye to keeping it that way, I added CI runs which build and test against liboqs main.
https://github.com/open-quantum-safe/liboqs-rust/pull/271 should be merged first.

feat: Update to liboqs 0.12.0

---

oqs-sys/build.rs

Currently, the build script will only compile the `oqs` target. This means that the cmake package config file is not generated. This means that the vendored CMake project can't be easily used as a dependency of a different CMake project.
This PR changes the behavior to build and execute the `install` target. I also remove the "build" folder to keep things a bit neater. 
```
/home/ubuntu/workspace/liboqs-rust/target/debug/build/oqs-sys-71d0b41005a2adce/out
├── build
│   ├── CMakeCache.txt
│   ├── CMakeFiles
│   │   └── <SNIP, lots of cmake stuff but NOT the config file>
│   ├── CPackConfig.cmake
│   ├── CPackSourceConfig.cmake
│   ├── Makefile
│   ├── cmake_install.cmake
│   ├── cmake_uninstall.cmake
│   ├── compile_commands.json
│   ├── include
│   │   └── oqs
│   ├── lib
│   │   └── …
```

fix: run install target during build

---

.github/workflows/ci.yml
oqs-sys/Cargo.toml
oqs-sys/build.rs
oqs/Cargo.toml

Allow liboqs-rust to use the OpenSSL pulled in from `openssl-sys`.
If a rust project wants to link several things against OpenSSL, it is easiest to use the standard `openssl-sys` package. This PR adds a new feature `vendored_openssl` that will allow the vendored_openssl to be pulled in.
I added this as a totally separate feature, which preserves the current `OPENSSL_ROOT_DIR` environment variable behavior. `openssl-sys` expects openssl to be specified with `OPENSSL_DIR`, so it would be a breaking change.
Alternately this "feature" could be the result if enabled both `openssl` and `vendored`. E.g., if you want a vendored liboqs then you might also want a vendored openssl?

feat: consume openssl from openssl-sys

---

oqs-sys/build.rs

This fixes a bug in the build script where a block filter is being added to the allow list instead of the block list.

fix: block filter added to block list, not allow list

---

.github/workflows/ci.yml

Recently, CI has been failing on Windows with Nightly Rust. CI is passing on all other configurations, including Windows with Beta Rust. This PR disables the Nightly Rust builds. As far as I can tell, this issue is not related to a change in liboqs or liboqs-rust.
I will periodically try re-enabling the Nightly build to see if the issue resolves itself. In the meantime, if somebody with more Rust knowledge has a fix, please feel to submit it!

ci: Disable nightly builds on Windows

---

.github/workflows/ci.yml

I guess that whatever changed in Nightly Rust has now made its way into Beta Rust. See https://github.com/open-quantum-safe/liboqs-rust/pull/282.

ci: exclude Windows / Beta Rust from CI
